export const EXPERIENCES = [
  {
    title: 'Agressive Solutions',
    initialDatetime: '03/2025',
    finalDatetime: '07/2025',
    tools: [
      'VueJs',
      'Vuex', 
      'VueRouter', 
      'Scrum', 
      'Agile', 
      'JSON', 
      'Kanbam', 
      'ChartJs', 
      'TailwindCSS',
      'Google Maps',
      'NodeJs',
      'Drizzle'
    ],
  },
  {
    title: 'TradeUp Group',
    initialDatetime: '07/2024',
    finalDatetime: '03/2025',
    tools: ['VueJs', 'Vuex', 'VueRouter', 'Scrum', 'Agile', 'JSON', 'Kanbam', 'TailwindCSS'],
  },
  {
    title: 'Confidential',
    initialDatetime: '07/2022',
    finalDatetime: '07/2024',
    tools: ['VueJs', 'Vuetify', 'Vuex', 'VueRouter', 'Scrum', 'Agile', 'JSON', 'TailwindCSS'],
  },
  {
    title: 'FarmTech',
    initialDatetime: '07/2021',
    finalDatetime: '07/2022',
    tools: [
      'VueJs',
      'Vuetify',
      'Vuex',
      'VueRouter',
      'Cypress',
      'JSON',
      'Mobile First',
      'TailwindCSS'
    ],
  },
  {
    title: 'Inking',
    initialDatetime: '09/2020',
    finalDatetime: '07/2021',
    tools: [
      'VueJs',
      'Vuetify',
      'Vuex',
      'VueRouter',
      'Cypress',
      'JSON',
      'Mobile First',
      'Java',
      'Spring Boot',
      'MySQL',
      'Swagger',
    ],
  },
];
